### ISSUE TITLE
Could there be any reason to use keywordsearch instead of offersearch if it's available?

### ISSUE THREAD

**Issue by shaunmaharaj** [elasticpath/alexa-skill#7]
Could there be any reason to use keywordsearch instead of offersearch if it's available?

_Originally posted by @shaunmaharaj in https://github.com/elasticpath/alexa-skill/pull/6_

**Comment by maennis-ep** [comment]
This should be done similar to the Storefront so that it uses the `offersearch` resource if it is available, otherwise it should fallback to `keywordsearch`.
